import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Regulatory-Compliant Drug Causality Assessment\n",
                "\n",
                "**Pharmacovigilance Analysis per FDA/EMA Guidelines**\n",
                "\n",
                "This tool assists in:\n",
                "- Adverse event detection\n",
                "- Pharmacovigilance screening  \n",
                "- Clinical report analysis\n",
                "- Regulatory compliance (FDA/EMA)\n",
                "\n",
                "## Features\n",
                "- WHO-UMC Causality Assessment\n",
                "- Naranjo ADR Probability Scale\n",
                "- Section-wise analysis (Abstract, Methods, Results, Discussion, Conclusion)\n",
                "- Drug-specific causality reports\n",
                "- Comprehensive Word document generation\n",
                "\n",
                "## Model Performance\n",
                "- F1 Score: 0.9759\n",
                "- Accuracy: 0.9759\n",
                "- Sensitivity: 0.9868\n",
                "- Specificity: 0.9650"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 1. Install Dependencies"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Install required packages\n",
                "!pip install torch transformers pandas numpy scikit-learn nltk PyPDF2 safetensors ipywidgets python-docx -q\n",
                "print('✓ All packages installed!')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 2. Import Libraries"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import sys\n",
                "from pathlib import Path\n",
                "sys.path.insert(0, str(Path.cwd() / 'src'))\n",
                "\n",
                "import os\n",
                "import json\n",
                "from datetime import datetime\n",
                "from regulatory_causality_report import create_regulatory_report\n",
                "\n",
                "print('✓ Libraries imported successfully!')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Upload PDF and Generate Regulatory Report\n",
                "\n",
                "Upload your PDF document to generate a comprehensive regulatory-compliant causality assessment report."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from ipywidgets import FileUpload, Button, VBox, HTML, Output\n",
                "from IPython.display import display, clear_output\n",
                "\n",
                "# Create upload widget\n",
                "upload_widget = FileUpload(accept='.pdf', multiple=False)\n",
                "analyze_button = Button(\n",
                "    description='Generate Regulatory Report',\n",
                "    button_style='success',\n",
                "    disabled=True,\n",
                "    tooltip='Upload a PDF first'\n",
                ")\n",
                "output_area = Output()\n",
                "\n",
                "uploaded_file_path = None\n",
                "\n",
                "def save_uploaded_file(change):\n",
                "    global uploaded_file_path\n",
                "    if upload_widget.value:\n",
                "        uploaded_file = list(upload_widget.value.values())[0]\n",
                "        filename = uploaded_file['metadata']['name']\n",
                "        content = uploaded_file['content']\n",
                "        \n",
                "        # Save to data/raw directory\n",
                "        os.makedirs('./data/raw', exist_ok=True)\n",
                "        uploaded_file_path = f'./data/raw/{filename}'\n",
                "        \n",
                "        with open(uploaded_file_path, 'wb') as f:\n",
                "            f.write(content)\n",
                "        \n",
                "        analyze_button.disabled = False\n",
                "        \n",
                "        with output_area:\n",
                "            clear_output()\n",
                "            print(f'✓ File uploaded: {filename}')\n",
                "            print(f'✓ Saved to: {uploaded_file_path}')\n",
                "            print('\\nClick \"Generate Regulatory Report\" to process.')\n",
                "            print('\\nThis will create:')\n",
                "            print('  - Comprehensive Word document with:')\n",
                "            print('    • Drug-specific causality analysis')\n",
                "            print('    • Section-wise breakdown (Abstract, Methods, Results, etc.)')\n",
                "            print('    • WHO-UMC Causality Categories')\n",
                "            print('    • Naranjo ADR Probability Scores')\n",
                "            print('    • FDA/EMA regulatory context')\n",
                "            print('    • Clinical significance assessments')\n",
                "            print('  - JSON summary with statistics')\n",
                "\n",
                "def analyze_pdf(b):\n",
                "    global uploaded_file_path\n",
                "    with output_area:\n",
                "        if not uploaded_file_path or not os.path.exists(uploaded_file_path):\n",
                "            print('⚠ Please upload a PDF file first!')\n",
                "            return\n",
                "        \n",
                "        clear_output()\n",
                "        print(f'Generating regulatory report for: {uploaded_file_path}\\n')\n",
                "        print('=' * 80)\n",
                "        print('This may take a few minutes...')\n",
                "        print('=' * 80)\n",
                "        \n",
                "        try:\n",
                "            # Generate regulatory report\n",
                "            doc_path, json_path = create_regulatory_report(uploaded_file_path)\n",
                "            \n",
                "            # Display results\n",
                "            print('\\n' + '=' * 80)\n",
                "            print('✓ REGULATORY REPORT GENERATED SUCCESSFULLY')\n",
                "            print('=' * 80)\n",
                "            \n",
                "            # Read and display summary\n",
                "            with open(json_path, 'r') as f:\n",
                "                summary = json.load(f)\n",
                "            \n",
                "            print(f\"\\nDocument: {summary['pdf_file']}\")\n",
                "            print(f\"Analysis Date: {summary['analysis_date']}\")\n",
                "            print(f\"\\nStatistics:\")\n",
                "            print(f\"  - Total Sentences: {summary['total_sentences']}\")\n",
                "            print(f\"  - Unique Drugs: {summary['total_drugs']}\")\n",
                "            print(f\"  - Unique Events: {summary['total_events']}\")\n",
                "            \n",
                "            print(f\"\\nKey Drugs Identified:\")\n",
                "            for drug_stat in summary['drug_statistics'][:10]:\n",
                "                print(f\"  • {drug_stat['drug']}: {drug_stat['related_count']} related sentences ({drug_stat['max_confidence']*100:.2f}% confidence)\")\n",
                "            \n",
                "            print(f\"\\nFiles Generated:\")\n",
                "            print(f\"  📄 Word Report: {doc_path}\")\n",
                "            print(f\"  📊 JSON Summary: {json_path}\")\n",
                "            \n",
                "            print(f\"\\n{'=' * 80}\")\n",
                "            print('The Word document contains:')\n",
                "            print('  ✓ Executive Summary')\n",
                "            print('  ✓ Key Drugs Identified with confidence scores')\n",
                "            print('  ✓ Quality Metrics')\n",
                "            print('  ✓ Detailed Drug-Event Analysis (organized by drug)')\n",
                "            print('  ✓ Section-wise causality statements')\n",
                "            print('  ✓ WHO-UMC Causality Categories')\n",
                "            print('  ✓ Naranjo ADR Probability Scores')\n",
                "            print('  ✓ FDA/EMA Regulatory Context')\n",
                "            print('  ✓ Clinical Significance Assessments')\n",
                "            print('=' * 80)\n",
                "            \n",
                "        except Exception as e:\n",
                "            print(f'❌ Error: {str(e)}')\n",
                "            import traceback\n",
                "            traceback.print_exc()\n",
                "\n",
                "upload_widget.observe(save_uploaded_file, names='value')\n",
                "analyze_button.on_click(analyze_pdf)\n",
                "\n",
                "display(VBox([\n",
                "    HTML('<h3>📄 Upload PDF for Regulatory Causality Assessment</h3>'),\n",
                "    HTML('<p><b>Generates comprehensive report with WHO-UMC and Naranjo assessments</b></p>'),\n",
                "    upload_widget,\n",
                "    analyze_button,\n",
                "    output_area\n",
                "]))"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. View Generated Reports\n",
                "\n",
                "List all generated regulatory reports."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import glob\n",
                "from pathlib import Path\n",
                "\n",
                "# Find all regulatory reports\n",
                "word_reports = glob.glob('./results/*_regulatory_report_*.docx')\n",
                "json_reports = glob.glob('./results/*_regulatory_summary_*.json')\n",
                "\n",
                "print('=' * 80)\n",
                "print('GENERATED REGULATORY REPORTS')\n",
                "print('=' * 80)\n",
                "\n",
                "if word_reports:\n",
                "    print(f'\\nWord Reports ({len(word_reports)}):') \n",
                "    for report in sorted(word_reports, reverse=True):\n",
                "        size = Path(report).stat().st_size / 1024\n",
                "        print(f'  📄 {Path(report).name} ({size:.1f} KB)')\n",
                "else:\n",
                "    print('\\nNo Word reports found yet.')\n",
                "\n",
                "if json_reports:\n",
                "    print(f'\\nJSON Summaries ({len(json_reports)}):')\n",
                "    for report in sorted(json_reports, reverse=True):\n",
                "        size = Path(report).stat().st_size / 1024\n",
                "        print(f'  📊 {Path(report).name} ({size:.1f} KB)')\n",
                "else:\n",
                "    print('\\nNo JSON summaries found yet.')\n",
                "\n",
                "print('\\n' + '=' * 80)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Batch Process Multiple PDFs\n",
                "\n",
                "Process all PDF files in the data/raw directory."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import glob\n",
                "\n",
                "# Find all PDF files\n",
                "pdf_files = glob.glob('./data/raw/*.pdf')\n",
                "\n",
                "if pdf_files:\n",
                "    print(f'Found {len(pdf_files)} PDF files\\n')\n",
                "    print('=' * 80)\n",
                "    \n",
                "    for i, pdf_path in enumerate(pdf_files, 1):\n",
                "        print(f'\\nProcessing {i}/{len(pdf_files)}: {Path(pdf_path).name}')\n",
                "        print('-' * 80)\n",
                "        \n",
                "        try:\n",
                "            doc_path, json_path = create_regulatory_report(pdf_path)\n",
                "            print(f'✓ Report generated: {Path(doc_path).name}')\n",
                "        except Exception as e:\n",
                "            print(f'✗ Error: {e}')\n",
                "    \n",
                "    print('\\n' + '=' * 80)\n",
                "    print('✓ BATCH PROCESSING COMPLETE')\n",
                "    print('=' * 80)\n",
                "else:\n",
                "    print('No PDF files found in ./data/raw/ directory')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 6. Understanding the Report\n",
                "\n",
                "### Report Structure\n",
                "\n",
                "The generated Word document contains:\n",
                "\n",
                "#### 1. Executive Summary\n",
                "- Total sentences analyzed\n",
                "- Drug-event sentences identified\n",
                "- Causality-related sentences\n",
                "- Unique drugs and events\n",
                "\n",
                "#### 2. Key Drugs Identified\n",
                "- List of all drugs with causality signals\n",
                "- Associated adverse events\n",
                "- Confidence scores\n",
                "- Number of related sentences\n",
                "\n",
                "#### 3. Quality Metrics\n",
                "- Model performance statistics\n",
                "- Confidence thresholds\n",
                "- Average confidence scores\n",
                "\n",
                "#### 4. Detailed Drug Analysis\n",
                "For each drug:\n",
                "- **Section-wise breakdown** (Abstract, Methods, Results, Discussion, Conclusion)\n",
                "- **Causality sentences** from each section\n",
                "- **Classification** (Related/Not Related)\n",
                "- **Confidence scores**\n",
                "- **WHO-UMC Causality Category**\n",
                "  - Certain/Definite\n",
                "  - Probable/Likely\n",
                "  - Possible\n",
                "  - Unlikely\n",
                "  - Conditional/Unclassified\n",
                "  - Unassessable/Unclassifiable\n",
                "- **Naranjo ADR Probability Score** (0-13 scale)\n",
                "  - Definite (≥9)\n",
                "  - Probable (5-8)\n",
                "  - Possible (1-4)\n",
                "  - Doubtful (≤0)\n",
                "\n",
                "#### 5. Regulatory Assessment\n",
                "For each drug:\n",
                "- **FDA/EMA Guidelines** context\n",
                "- **Clinical Significance** explanation\n",
                "- **Recommended Actions**\n",
                "  - Risk Management Plan (RMP)\n",
                "  - Periodic Safety Update Report (PSUR)\n",
                "  - Label updates\n",
                "  - Post-marketing surveillance\n",
                "\n",
                "### Causality Assessment Scales\n",
                "\n",
                "#### WHO-UMC Causality Categories\n",
                "1. **Certain**: Clear temporal relationship, no alternative explanation\n",
                "2. **Probable/Likely**: Reasonable time relationship, unlikely other causes\n",
                "3. **Possible**: Reasonable time relationship, other factors possible\n",
                "4. **Unlikely**: Temporal relationship exists but other factors more likely\n",
                "5. **Conditional/Unclassified**: More data needed\n",
                "6. **Unassessable**: Cannot be judged\n",
                "\n",
                "#### Naranjo ADR Probability Scale\n",
                "- Score range: -4 to +13\n",
                "- Based on 10 questions about the adverse drug reaction\n",
                "- Categories:\n",
                "  - **Definite**: ≥9 points\n",
                "  - **Probable**: 5-8 points\n",
                "  - **Possible**: 1-4 points\n",
                "  - **Doubtful**: ≤0 points"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook
with open('drug_causality_regulatory.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print("✓ Enhanced regulatory notebook created: drug_causality_regulatory.ipynb")
